[package]
name = "mini-dir"
version = "0.1.0"
authors = ["yxqsnz <73546477+yxqsnz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
